'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type MyAlertCustomEvent, type MyDropdownCustomEvent, type MyInputCustomEvent, type MyModalCustomEvent } from "@stencil-kit/core";
import type { Components } from "@stencil-kit/core/dist/components";
import { MyAlert as MyAlertElement, defineCustomElement as defineMyAlert } from "@stencil-kit/core/dist/components/my-alert.js";
import { MyBadge as MyBadgeElement, defineCustomElement as defineMyBadge } from "@stencil-kit/core/dist/components/my-badge.js";
import { MyButton as MyButtonElement, defineCustomElement as defineMyButton } from "@stencil-kit/core/dist/components/my-button.js";
import { MyCard as MyCardElement, defineCustomElement as defineMyCard } from "@stencil-kit/core/dist/components/my-card.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@stencil-kit/core/dist/components/my-component.js";
import { MyDropdown as MyDropdownElement, defineCustomElement as defineMyDropdown } from "@stencil-kit/core/dist/components/my-dropdown.js";
import { MyInput as MyInputElement, defineCustomElement as defineMyInput } from "@stencil-kit/core/dist/components/my-input.js";
import { MyModal as MyModalElement, defineCustomElement as defineMyModal } from "@stencil-kit/core/dist/components/my-modal.js";

export type MyAlertEvents = { onMyDismiss: EventName<MyAlertCustomEvent<void>> };

export const MyAlert: StencilReactComponent<MyAlertElement, MyAlertEvents, Components.MyAlert> = /*@__PURE__*/ createComponent<MyAlertElement, MyAlertEvents, Components.MyAlert>({
    tagName: 'my-alert',
    elementClass: MyAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyDismiss: 'myDismiss' } as MyAlertEvents,
    defineCustomElement: defineMyAlert
});

export type MyBadgeEvents = NonNullable<unknown>;

export const MyBadge: StencilReactComponent<MyBadgeElement, MyBadgeEvents, Components.MyBadge> = /*@__PURE__*/ createComponent<MyBadgeElement, MyBadgeEvents, Components.MyBadge>({
    tagName: 'my-badge',
    elementClass: MyBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyBadgeEvents,
    defineCustomElement: defineMyBadge
});

export type MyButtonEvents = NonNullable<unknown>;

export const MyButton: StencilReactComponent<MyButtonElement, MyButtonEvents, Components.MyButton> = /*@__PURE__*/ createComponent<MyButtonElement, MyButtonEvents, Components.MyButton>({
    tagName: 'my-button',
    elementClass: MyButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyButtonEvents,
    defineCustomElement: defineMyButton
});

export type MyCardEvents = NonNullable<unknown>;

export const MyCard: StencilReactComponent<MyCardElement, MyCardEvents, Components.MyCard> = /*@__PURE__*/ createComponent<MyCardElement, MyCardEvents, Components.MyCard>({
    tagName: 'my-card',
    elementClass: MyCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyCardEvents,
    defineCustomElement: defineMyCard
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents, Components.MyComponent> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents, Components.MyComponent>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type MyDropdownEvents = { onMyChange: EventName<MyDropdownCustomEvent<string>> };

export const MyDropdown: StencilReactComponent<MyDropdownElement, MyDropdownEvents, Components.MyDropdown> = /*@__PURE__*/ createComponent<MyDropdownElement, MyDropdownEvents, Components.MyDropdown>({
    tagName: 'my-dropdown',
    elementClass: MyDropdownElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyChange: 'myChange' } as MyDropdownEvents,
    defineCustomElement: defineMyDropdown
});

export type MyInputEvents = {
    onMyChange: EventName<MyInputCustomEvent<string>>,
    onMyBlur: EventName<MyInputCustomEvent<void>>
};

export const MyInput: StencilReactComponent<MyInputElement, MyInputEvents, Components.MyInput> = /*@__PURE__*/ createComponent<MyInputElement, MyInputEvents, Components.MyInput>({
    tagName: 'my-input',
    elementClass: MyInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMyChange: 'myChange',
        onMyBlur: 'myBlur'
    } as MyInputEvents,
    defineCustomElement: defineMyInput
});

export type MyModalEvents = { onMyClose: EventName<MyModalCustomEvent<void>> };

export const MyModal: StencilReactComponent<MyModalElement, MyModalEvents, Components.MyModal> = /*@__PURE__*/ createComponent<MyModalElement, MyModalEvents, Components.MyModal>({
    tagName: 'my-modal',
    elementClass: MyModalElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMyClose: 'myClose' } as MyModalEvents,
    defineCustomElement: defineMyModal
});
